### ISSUE TITLE
coupling DualSPHysics with Moordyn

### ISSUE THREAD

**Issue by chenxin202** [imestevez/MoorDynPlus#1]
Excuse me
I am very interested in your research about how to couple DualSPHysics with MoorDyn.   And l tried to finish the work by myself. To date, I have completed the work on the combining DualSPHysics and MoorDyn DLL. According to the post processing results, It can be seen clearly that the motion of floating body can be limited indeed. But I don’t know how to visualize the mooring lines. I heard you had achieved big success on this aspect.Could you give me some suggestions on how to visualize these mooring lines based on the coupling between DualSPHysics and MoorDyn. 
Best Regards.
Xin Chen

**Comment by imestevez** [comment]
Hello Xin Chen,
The visualization of mooring lines is managed by DualSPHysics. Each mooring
line of MoorDyn+ is created by segments divided in nodes. DualSPHysics
generates the *.vtk* of mooring lines using each node position. These *.vkt*
will be saved in path *CaseName_out**/MooringsVtk*.
Regards,
Iván

**Comment by 159407bobo** [comment]
Excuse me, I want to know how to couple DualSPHysics to MoorDyn
